"""Architecture-view residual Particle Transformer components.

Step 1 exposes validated configs, raw HLT input handling, PN/PFN/PCNN
per-particle view branches, and a baseline-safe view-fusion module.  Later
steps wire these views into the real HLT ParT embedding space.
"""

from __future__ import annotations

from .config import (
    ARCHITECTURE_VIEW_BACKGROUND_LABEL,
    ARCHITECTURE_VIEW_BRANCHES,
    ARCHITECTURE_VIEW_BRANCH_PCNN,
    ARCHITECTURE_VIEW_BRANCH_PFN,
    ARCHITECTURE_VIEW_BRANCH_PN,
    ARCHITECTURE_VIEW_BINARY_LABEL_FILTER,
    ARCHITECTURE_VIEW_DEFAULT_PILOT_VARIANTS,
    ARCHITECTURE_VIEW_HLT_DEGRADATION_STRENGTH,
    ARCHITECTURE_VIEW_LABEL_NAMES,
    ARCHITECTURE_VIEW_PART_CONTRACT,
    ARCHITECTURE_VIEW_PART_EXPERIMENT_NAME,
    ARCHITECTURE_VIEW_PART_STEP,
    ARCHITECTURE_VIEW_PRIMARY_METRIC,
    ARCHITECTURE_VIEW_PRIMARY_METRIC_DIRECTION,
    ARCHITECTURE_VIEW_RAW_FEATURE_NAMES,
    ARCHITECTURE_VIEW_SIGNAL_LABEL,
    ARCHITECTURE_VIEW_VARIANT_ALL_VIEWS,
    ARCHITECTURE_VIEW_VARIANT_BASELINE_RECHECK,
    ARCHITECTURE_VIEW_VARIANT_CONTEXT_MLP_CONTROL,
    ARCHITECTURE_VIEW_VARIANT_PCNN_ONLY,
    ARCHITECTURE_VIEW_VARIANT_PFN_ONLY,
    ARCHITECTURE_VIEW_VARIANT_PN_ONLY,
    ARCHITECTURE_VIEW_VARIANT_RANDOM_VIEW_CONTROL,
    ARCHITECTURE_VIEW_VARIANTS,
    ArchitectureViewConfig,
    ArchitectureViewVariantSpec,
    architecture_view_config_manifest,
    architecture_view_variant_specs,
    enabled_views_for_variant,
    normalize_architecture_view_branch,
    normalize_architecture_view_variant,
)
from .inputs import (
    ARCHITECTURE_VIEW_INPUTS_CONTRACT,
    ArchitectureViewInputs,
    architecture_view_inputs_from_batch,
    build_architecture_view_quality_features,
    sanitize_architecture_view_tokens,
    wrap_architecture_view_phi,
)
from .branches import (
    ARCHITECTURE_VIEW_BRANCHES_CONTRACT,
    ArchitectureViewBranchBank,
    ArchitectureViewBranchOutput,
    PCNNViewBranch,
    PFNViewBranch,
    PNViewBranch,
    branch_output_shapes,
    build_architecture_view_branch,
)
from .fusion import (
    ARCHITECTURE_VIEW_FUSION_CONTRACT,
    ArchitectureViewFusion,
    ArchitectureViewFusionOutput,
    ArchitectureViewParticleViews,
    architecture_view_branch_order,
    expected_combined_view_dim,
)
from .model import (
    ARCHITECTURE_VIEW_MODEL_CONTRACT,
    ARCHITECTURE_VIEW_MODEL_STEP,
    ArchitectureViewResidualParT,
    ArchitectureViewResidualPartOutput,
    build_architecture_view_residual_part,
)
from .checkpoint import (
    ARCHITECTURE_VIEW_CHECKPOINT_CONTRACT,
    ARCHITECTURE_VIEW_CHECKPOINT_STEP,
    compute_architecture_view_init_logit_diff_vs_baseline,
    load_architecture_view_hlt_part_checkpoint,
    sha256_file,
    warm_start_architecture_view_part_model,
)
from .train import (
    ARCHITECTURE_VIEW_SELECTION_METRICS,
    ARCHITECTURE_VIEW_TRAIN_CONTRACT,
    ARCHITECTURE_VIEW_TRAIN_STEP,
    ArchitectureViewTaggerTrainConfig,
    architecture_view_label_filter_names_to_indices,
    load_architecture_view_tagger_checkpoint,
    run_architecture_view_tagger_epoch,
    train_architecture_view_tagger,
)
from .reports import (
    ARCHITECTURE_VIEW_REPORT_CONTRACT,
    ARCHITECTURE_VIEW_REPORT_STEP,
    ARCHITECTURE_VIEW_VALIDATION_THRESHOLD_METRIC,
    ArchitectureViewPartReportConfig,
    build_architecture_view_part_report,
)

__all__ = [
    "ARCHITECTURE_VIEW_BACKGROUND_LABEL",
    "ARCHITECTURE_VIEW_BRANCHES",
    "ARCHITECTURE_VIEW_BRANCHES_CONTRACT",
    "ARCHITECTURE_VIEW_BINARY_LABEL_FILTER",
    "ARCHITECTURE_VIEW_BRANCH_PCNN",
    "ARCHITECTURE_VIEW_BRANCH_PFN",
    "ARCHITECTURE_VIEW_BRANCH_PN",
    "ARCHITECTURE_VIEW_DEFAULT_PILOT_VARIANTS",
    "ARCHITECTURE_VIEW_FUSION_CONTRACT",
    "ARCHITECTURE_VIEW_CHECKPOINT_CONTRACT",
    "ARCHITECTURE_VIEW_CHECKPOINT_STEP",
    "ARCHITECTURE_VIEW_HLT_DEGRADATION_STRENGTH",
    "ARCHITECTURE_VIEW_INPUTS_CONTRACT",
    "ARCHITECTURE_VIEW_LABEL_NAMES",
    "ARCHITECTURE_VIEW_PART_CONTRACT",
    "ARCHITECTURE_VIEW_PART_EXPERIMENT_NAME",
    "ARCHITECTURE_VIEW_PART_STEP",
    "ARCHITECTURE_VIEW_MODEL_CONTRACT",
    "ARCHITECTURE_VIEW_MODEL_STEP",
    "ARCHITECTURE_VIEW_PRIMARY_METRIC",
    "ARCHITECTURE_VIEW_PRIMARY_METRIC_DIRECTION",
    "ARCHITECTURE_VIEW_RAW_FEATURE_NAMES",
    "ARCHITECTURE_VIEW_REPORT_CONTRACT",
    "ARCHITECTURE_VIEW_REPORT_STEP",
    "ARCHITECTURE_VIEW_SELECTION_METRICS",
    "ARCHITECTURE_VIEW_SIGNAL_LABEL",
    "ARCHITECTURE_VIEW_TRAIN_CONTRACT",
    "ARCHITECTURE_VIEW_TRAIN_STEP",
    "ARCHITECTURE_VIEW_VALIDATION_THRESHOLD_METRIC",
    "ARCHITECTURE_VIEW_VARIANT_ALL_VIEWS",
    "ARCHITECTURE_VIEW_VARIANT_BASELINE_RECHECK",
    "ARCHITECTURE_VIEW_VARIANT_CONTEXT_MLP_CONTROL",
    "ARCHITECTURE_VIEW_VARIANT_PCNN_ONLY",
    "ARCHITECTURE_VIEW_VARIANT_PFN_ONLY",
    "ARCHITECTURE_VIEW_VARIANT_PN_ONLY",
    "ARCHITECTURE_VIEW_VARIANT_RANDOM_VIEW_CONTROL",
    "ARCHITECTURE_VIEW_VARIANTS",
    "ArchitectureViewBranchBank",
    "ArchitectureViewBranchOutput",
    "ArchitectureViewConfig",
    "ArchitectureViewFusion",
    "ArchitectureViewFusionOutput",
    "ArchitectureViewInputs",
    "ArchitectureViewParticleViews",
    "ArchitectureViewPartReportConfig",
    "ArchitectureViewResidualParT",
    "ArchitectureViewResidualPartOutput",
    "ArchitectureViewTaggerTrainConfig",
    "ArchitectureViewVariantSpec",
    "PCNNViewBranch",
    "PFNViewBranch",
    "PNViewBranch",
    "architecture_view_branch_order",
    "architecture_view_config_manifest",
    "architecture_view_inputs_from_batch",
    "architecture_view_label_filter_names_to_indices",
    "architecture_view_variant_specs",
    "branch_output_shapes",
    "build_architecture_view_part_report",
    "build_architecture_view_branch",
    "build_architecture_view_residual_part",
    "build_architecture_view_quality_features",
    "enabled_views_for_variant",
    "expected_combined_view_dim",
    "compute_architecture_view_init_logit_diff_vs_baseline",
    "load_architecture_view_hlt_part_checkpoint",
    "load_architecture_view_tagger_checkpoint",
    "normalize_architecture_view_branch",
    "normalize_architecture_view_variant",
    "run_architecture_view_tagger_epoch",
    "sanitize_architecture_view_tokens",
    "sha256_file",
    "train_architecture_view_tagger",
    "warm_start_architecture_view_part_model",
    "wrap_architecture_view_phi",
]
