#!/usr/bin/env bash
# Map the PDV3 HLT-profile experiment contract onto the existing PD10 teacher tools.
#
# Source this after common.sh and before invoking any run_pd10_* script. The
# PD10 Python code remains the implementation of teacher training/caching, but
# every path and split-size-sensitive environment variable points at the PDV3
# root and Step 1 artifacts.

set -euo pipefail

export PD10_DATA_DIR="${PDV3_DATA_DIR}"
export PD10_ROOT="${PDV3_ROOT}"
export PD10_SPLIT_MANIFEST_DIR="${PDV3_SPLIT_MANIFEST_DIR}"
export PD10_MANIFEST_PATH="${PDV3_MANIFEST_PATH}"
export PD10_HLT_CACHE_DIR="${PDV3_HLT_CACHE_DIR}"
export PD10_AUDIT_DIR="${PDV3_AUDIT_DIR}"
export PD10_STEP2_AUDIT_DIR="${PDV3_STEP1_AUDIT_DIR}"
export PD10_TEACHERS_DIR="${PDV3_TEACHERS_DIR}"
export PD10_TEACHER_LOGITS_DIR="${PDV3_TEACHER_LOGITS_DIR}"
export PD10_TEACHER_REPRESENTATIONS_DIR="${PDV3_TEACHER_REPRESENTATIONS_DIR}"
export PD10_V2_ROOT="${PDV3_V2_ROOT}"
export PD10_V2_TEACHERS_DIR="${PDV3_TEACHERS_DIR}"
export PD10_V2_TEACHER_LOGITS_DIR="${PDV3_TEACHER_LOGITS_DIR}"
export PD10_V2_TEACHER_REPRESENTATIONS_DIR="${PDV3_TEACHER_REPRESENTATIONS_DIR}"
export PD10_MODEL_TRAIN_SIZE="${PDV3_MODEL_TRAIN_SIZE}"
export PD10_MODEL_VAL_SIZE="${PDV3_MODEL_VAL_SIZE}"
export PD10_STACK_TRAIN_SIZE="${PDV3_STACK_TRAIN_SIZE}"
export PD10_STACK_VAL_SIZE="${PDV3_STACK_VAL_SIZE}"
export PD10_FINAL_TEST_SIZE="${PDV3_FINAL_TEST_SIZE}"
export PD10_HLT_SPLITS="${PDV3_HLT_SPLITS}"
export PD10_HLT_PROFILE="${PDV3_HLT_PROFILE}"
export PD10_HLT_DEGRADATION_STRENGTH="${PDV3_HLT_DEGRADATION_STRENGTH}"
export PD10_TEACHER_TARGETS="${PDV3_TEACHER_TARGETS}"
export PD10_TEACHER_LOGIT_TARGETS="${PDV3_TEACHER_LOGIT_TARGETS}"
export PD10_TEACHER_LOGIT_SPLITS="${PDV3_TEACHER_LOGIT_SPLITS}"
export PD10_DUAL_VIEW_PREDICT_SPLITS="${PDV3_DUAL_VIEW_PREDICT_SPLITS}"
export PD10_V2_PARTICLE_DUAL_VIEW_CACHE_SPLITS="${PDV3_V2_PARTICLE_DUAL_VIEW_CACHE_SPLITS}"
export PD10_HLT_TEACHER_SEED="${PDV3_HLT_TEACHER_SEED}"
export PD10_OFFLINE_TEACHER_SEED="${PDV3_OFFLINE_TEACHER_SEED}"
export PD10_DUAL_VIEW_TEACHER_SEED="${PDV3_DUAL_VIEW_TEACHER_SEED}"
export PD10_V2_PARTICLE_DUAL_VIEW_TEACHER_SEED="${PDV3_V2_PARTICLE_DUAL_VIEW_TEACHER_SEED}"
export PD10_HLT_TEACHER_SOURCE_CHECKPOINT="${PDV3_HLT_TEACHER_SOURCE_CHECKPOINT}"
export PD10_HLT_TEACHER_SOURCE_REPORT="${PDV3_HLT_TEACHER_SOURCE_REPORT}"
export PD10_HLT_TEACHER_SOURCE_FINAL_TEST_REPORT="${PDV3_HLT_TEACHER_SOURCE_FINAL_TEST_REPORT}"
export PD10_OFFLINE_TEACHER_SOURCE_CHECKPOINT="${PDV3_OFFLINE_TEACHER_SOURCE_CHECKPOINT}"
export PD10_OFFLINE_TEACHER_SOURCE_REPORT="${PDV3_OFFLINE_TEACHER_SOURCE_REPORT}"
export PD10_OFFLINE_TEACHER_SOURCE_FINAL_TEST_REPORT="${PDV3_OFFLINE_TEACHER_SOURCE_FINAL_TEST_REPORT}"
export PD10_STUDENT_WARM_START_BASELINE_CHECKPOINT="${PDV3_TEACHERS_DIR}/hlt_part_teacher_10class/best_model_val.pt"
export PD10_DUAL_VIEW_TEACHER_DIR="${PDV3_TEACHERS_DIR}/dual_view_logit_teacher_10class"
export PD10_DUAL_VIEW_TEACHER_LOGITS_DIR="${PDV3_TEACHER_LOGITS_DIR}/dual_view_logit_teacher_10class"
export PD10_V2_PARTICLE_DUAL_VIEW_TEACHER_DIR="${PDV3_TEACHERS_DIR}/particle_dual_view_teacher_10class"
export PD10_V2_PARTICLE_DUAL_VIEW_TEACHER_CHECKPOINT="${PD10_V2_PARTICLE_DUAL_VIEW_TEACHER_DIR}/best_model_val.pt"
