#!/usr/bin/env bash
# Run one Step 22 Version B subtoken tagger with privileged offline training signals.

#SBATCH --job-name=subtoken_distill
#SBATCH --output=fresh_check_logs/%x_%j.out
#SBATCH --error=fresh_check_logs/%x_%j.err
#SBATCH --partition=tier3
#SBATCH --time=2-12:00:00
#SBATCH --mem=160G
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8

set -euo pipefail
IFS=$'\n\t'

: "${PROJECT_DIR:=/home/ryreu/atlas/Fresh_check}"
SCRIPT_DIR="${PROJECT_DIR}/sbatch"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

: "${SUBTOKEN_PART_DISTILL_ROOT:=${OUTPUT_ROOT}/subtoken_part_version_b}"
: "${SUBTOKEN_PART_DISTILL_NAME:=subtoken_gate_context_distill}"
: "${SUBTOKEN_PART_DISTILL_DIR:=${SUBTOKEN_PART_DISTILL_ROOT}/${SUBTOKEN_PART_DISTILL_NAME}}"
: "${SUBTOKEN_PART_DISTILL_HLT_CACHE_DIR:=${HLT_CACHE_DIR}}"
: "${SUBTOKEN_PART_DISTILL_MANIFEST_PATH:=${MANIFEST_PATH}}"
: "${SUBTOKEN_PART_DISTILL_OFFLINE_TEACHER_CHECKPOINT:=${OFFLINE_TEACHER_DIR}/best_model_val.pt}"
: "${SUBTOKEN_PART_DISTILL_OFFLINE_TEACHER_ARCHITECTURE:=part}"
: "${SUBTOKEN_PART_DISTILL_TEACHER_DEVICE:=}"
: "${SUBTOKEN_PART_DISTILL_TEACHER_MAX_CONSTITS:=128}"
: "${SUBTOKEN_PART_DISTILL_TEACHER_WEIGHT_THRESHOLD:=0.0}"
: "${SUBTOKEN_PART_DISTILL_NON_STRICT_TEACHER_CHECKPOINT:=0}"
: "${SUBTOKEN_PART_DISTILL_DISTILLATION_TEMPERATURE:=2.0}"
: "${SUBTOKEN_PART_DISTILL_DISTILLATION_WEIGHT:=0.5}"
: "${SUBTOKEN_PART_DISTILL_CLASSIFICATION_WEIGHT:=1.0}"
: "${SUBTOKEN_PART_DISTILL_MODALITY_RESIDUAL_WEIGHT:=0.0}"
: "${SUBTOKEN_PART_DISTILL_MODALITY_RESIDUAL_TARGET_MODE:=jet_plus_nearest}"
: "${SUBTOKEN_PART_DISTILL_MODALITY_RESIDUAL_HUBER_BETA:=1.0}"
: "${SUBTOKEN_PART_DISTILL_GATE_RESIDUAL_REGULARIZATION_WEIGHT:=0.0}"
: "${SUBTOKEN_PART_DISTILL_GATE_RESIDUAL_TEMPERATURE:=1.0}"
: "${SUBTOKEN_PART_DISTILL_MASKED_SUBTOKEN_WEIGHT:=0.0}"
: "${SUBTOKEN_PART_DISTILL_MASKED_SUBTOKEN_TARGET_MODE:=hlt_self}"
: "${SUBTOKEN_PART_DISTILL_MASKED_SUBTOKEN_PROBABILITY:=0.15}"
: "${SUBTOKEN_PART_DISTILL_MASKED_SUBTOKEN_HUBER_BETA:=1.0}"
: "${SUBTOKEN_PART_DISTILL_MASKED_SUBTOKEN_MAX_MATCH_DELTA_R:=0.4}"
: "${SUBTOKEN_PART_DISTILL_VERIFY_OFFLINE_LABEL_BRANCHES:=0}"
: "${SUBTOKEN_PART_DISTILL_READ_CHUNK_SIZE:=50000}"

: "${SUBTOKEN_PART_DISTILL_LABEL_FILTER_NAMES:=0 1}"
: "${SUBTOKEN_PART_DISTILL_LABEL_NAMES:=QCD Hgg}"
: "${SUBTOKEN_PART_DISTILL_NUM_CLASSES:=2}"
: "${SUBTOKEN_PART_DISTILL_SEED:=3607}"
: "${SUBTOKEN_PART_DISTILL_BATCH_SIZE:=64}"
: "${SUBTOKEN_PART_DISTILL_EVAL_BATCH_SIZE:=128}"
: "${SUBTOKEN_PART_DISTILL_EPOCHS:=45}"
: "${SUBTOKEN_PART_DISTILL_LR:=0.0003}"
: "${SUBTOKEN_PART_DISTILL_WEIGHT_DECAY:=0.0001}"
: "${SUBTOKEN_PART_DISTILL_NUM_WORKERS:=${NUM_WORKERS}}"
: "${SUBTOKEN_PART_DISTILL_DEVICE:=${DEVICE}}"
: "${SUBTOKEN_PART_DISTILL_GRAD_CLIP_NORM:=${GRAD_CLIP_NORM}}"
: "${SUBTOKEN_PART_DISTILL_EARLY_STOP_PATIENCE:=6}"
: "${SUBTOKEN_PART_DISTILL_MAX_TRAIN_BATCHES:=}"
: "${SUBTOKEN_PART_DISTILL_MAX_VAL_BATCHES:=}"
: "${SUBTOKEN_PART_DISTILL_MAX_STACK_VAL_BATCHES:=}"
: "${SUBTOKEN_PART_DISTILL_MAX_FINAL_TEST_BATCHES:=}"
: "${SUBTOKEN_PART_DISTILL_MODEL_TRAIN_SIZE:=500000}"
: "${SUBTOKEN_PART_DISTILL_MODEL_VAL_SIZE:=150000}"
: "${SUBTOKEN_PART_DISTILL_STACK_VAL_SIZE:=150000}"
: "${SUBTOKEN_PART_DISTILL_FINAL_TEST_SIZE:=500000}"
: "${SUBTOKEN_PART_DISTILL_SELECTION_METRIC:=fpr_at_signal_eff_0p50}"
: "${SUBTOKEN_PART_DISTILL_VARIANT:=subtoken_gate_context}"
: "${SUBTOKEN_PART_DISTILL_EMBED_DIM:=128}"
: "${SUBTOKEN_PART_DISTILL_LOCAL_LAYERS:=1}"
: "${SUBTOKEN_PART_DISTILL_LOCAL_HEADS:=4}"
: "${SUBTOKEN_PART_DISTILL_CONTEXT_LAYERS:=2}"
: "${SUBTOKEN_PART_DISTILL_CONTEXT_HEADS:=4}"
: "${SUBTOKEN_PART_DISTILL_GLOBAL_LAYERS:=6}"
: "${SUBTOKEN_PART_DISTILL_GLOBAL_HEADS:=8}"
: "${SUBTOKEN_PART_DISTILL_GATE_MODE:=context_softmax}"
: "${SUBTOKEN_PART_DISTILL_LOCAL_POOL_MODE:=learned_query}"
: "${SUBTOKEN_PART_DISTILL_DISABLE_PAIRWISE_BIAS:=0}"
: "${SUBTOKEN_PART_DISTILL_DISABLE_PARTICLE_ANCHOR:=0}"
: "${SUBTOKEN_PART_DISTILL_DISABLE_MODALITY_TYPE_EMBEDDINGS:=0}"
: "${SUBTOKEN_PART_DISTILL_USE_PT_RANK_EMBEDDING:=0}"
: "${SUBTOKEN_PART_DISTILL_MODALITY_DROPOUT:=0.0}"
: "${SUBTOKEN_PART_DISTILL_DROPOUT:=0.05}"
: "${SUBTOKEN_PART_DISTILL_ATTENTION_DROPOUT:=0.05}"
: "${SUBTOKEN_PART_DISTILL_ANCHOR_SOURCE:=raw}"
: "${SUBTOKEN_PART_DISTILL_DISABLE_PART_STYLE_DERIVED_FEATURES:=0}"
: "${SUBTOKEN_PART_DISTILL_NO_AMP:=0}"
: "${SUBTOKEN_PART_DISTILL_COMPILE_MODEL:=0}"
: "${SUBTOKEN_PART_DISTILL_SKIP_HLT_HASH_CHECK:=0}"
: "${SUBTOKEN_PART_DISTILL_CONFIRM_FINAL_TEST:=1}"

fresh_setup "$@"
fresh_require_data_dir
fresh_require_file "scripts/train_subtoken_part_distill.py"
fresh_require_file "${SUBTOKEN_PART_DISTILL_MANIFEST_PATH}"
fresh_require_file "${SUBTOKEN_PART_DISTILL_OFFLINE_TEACHER_CHECKPOINT}"
for split in model_train model_val stack_val final_test; do
  fresh_require_file "${SUBTOKEN_PART_DISTILL_HLT_CACHE_DIR}/${split}_fixed_hlt.npz"
  fresh_require_file "${SUBTOKEN_PART_DISTILL_HLT_CACHE_DIR}/${split}_fixed_hlt_metadata.json"
done
fresh_claim_new_dir "${SUBTOKEN_PART_DISTILL_DIR}"

fresh_split_words label_filter_args "${SUBTOKEN_PART_DISTILL_LABEL_FILTER_NAMES}"
fresh_split_words label_name_args "${SUBTOKEN_PART_DISTILL_LABEL_NAMES}"

cmd=(
  "${PYTHON_BIN}" "-u" "scripts/train_subtoken_part_distill.py"
  --output-dir "${SUBTOKEN_PART_DISTILL_DIR}"
  --hlt-cache-dir "${SUBTOKEN_PART_DISTILL_HLT_CACHE_DIR}"
  --manifest-path "${SUBTOKEN_PART_DISTILL_MANIFEST_PATH}"
  --data-dir "${DATA_DIR}"
  --offline-teacher-checkpoint "${SUBTOKEN_PART_DISTILL_OFFLINE_TEACHER_CHECKPOINT}"
  --offline-teacher-architecture "${SUBTOKEN_PART_DISTILL_OFFLINE_TEACHER_ARCHITECTURE}"
  --teacher-max-constits "${SUBTOKEN_PART_DISTILL_TEACHER_MAX_CONSTITS}"
  --teacher-weight-threshold "${SUBTOKEN_PART_DISTILL_TEACHER_WEIGHT_THRESHOLD}"
  --distillation-temperature "${SUBTOKEN_PART_DISTILL_DISTILLATION_TEMPERATURE}"
  --distillation-weight "${SUBTOKEN_PART_DISTILL_DISTILLATION_WEIGHT}"
  --classification-weight "${SUBTOKEN_PART_DISTILL_CLASSIFICATION_WEIGHT}"
  --modality-residual-weight "${SUBTOKEN_PART_DISTILL_MODALITY_RESIDUAL_WEIGHT}"
  --modality-residual-target-mode "${SUBTOKEN_PART_DISTILL_MODALITY_RESIDUAL_TARGET_MODE}"
  --modality-residual-huber-beta "${SUBTOKEN_PART_DISTILL_MODALITY_RESIDUAL_HUBER_BETA}"
  --gate-residual-regularization-weight "${SUBTOKEN_PART_DISTILL_GATE_RESIDUAL_REGULARIZATION_WEIGHT}"
  --gate-residual-temperature "${SUBTOKEN_PART_DISTILL_GATE_RESIDUAL_TEMPERATURE}"
  --masked-subtoken-weight "${SUBTOKEN_PART_DISTILL_MASKED_SUBTOKEN_WEIGHT}"
  --masked-subtoken-target-mode "${SUBTOKEN_PART_DISTILL_MASKED_SUBTOKEN_TARGET_MODE}"
  --masked-subtoken-probability "${SUBTOKEN_PART_DISTILL_MASKED_SUBTOKEN_PROBABILITY}"
  --masked-subtoken-huber-beta "${SUBTOKEN_PART_DISTILL_MASKED_SUBTOKEN_HUBER_BETA}"
  --masked-subtoken-max-match-delta-r "${SUBTOKEN_PART_DISTILL_MASKED_SUBTOKEN_MAX_MATCH_DELTA_R}"
  --read-chunk-size "${SUBTOKEN_PART_DISTILL_READ_CHUNK_SIZE}"
  --train-split model_train
  --val-split model_val
  --stack-val-split stack_val
  --final-test-split final_test
  --confirm-split-settings
  --seed "${SUBTOKEN_PART_DISTILL_SEED}"
  --batch-size "${SUBTOKEN_PART_DISTILL_BATCH_SIZE}"
  --eval-batch-size "${SUBTOKEN_PART_DISTILL_EVAL_BATCH_SIZE}"
  --epochs "${SUBTOKEN_PART_DISTILL_EPOCHS}"
  --lr "${SUBTOKEN_PART_DISTILL_LR}"
  --weight-decay "${SUBTOKEN_PART_DISTILL_WEIGHT_DECAY}"
  --num-workers "${SUBTOKEN_PART_DISTILL_NUM_WORKERS}"
  --device "${SUBTOKEN_PART_DISTILL_DEVICE}"
  --grad-clip-norm "${SUBTOKEN_PART_DISTILL_GRAD_CLIP_NORM}"
  --early-stop-patience "${SUBTOKEN_PART_DISTILL_EARLY_STOP_PATIENCE}"
  --max-train-jets "${SUBTOKEN_PART_DISTILL_MODEL_TRAIN_SIZE}"
  --max-val-jets "${SUBTOKEN_PART_DISTILL_MODEL_VAL_SIZE}"
  --max-stack-val-jets "${SUBTOKEN_PART_DISTILL_STACK_VAL_SIZE}"
  --max-final-test-jets "${SUBTOKEN_PART_DISTILL_FINAL_TEST_SIZE}"
  --selection-metric "${SUBTOKEN_PART_DISTILL_SELECTION_METRIC}"
  --num-classes "${SUBTOKEN_PART_DISTILL_NUM_CLASSES}"
  --label-names "${label_name_args[@]}"
  --label-filter-names "${label_filter_args[@]}"
  --variant "${SUBTOKEN_PART_DISTILL_VARIANT}"
  --embed-dim "${SUBTOKEN_PART_DISTILL_EMBED_DIM}"
  --local-layers "${SUBTOKEN_PART_DISTILL_LOCAL_LAYERS}"
  --local-heads "${SUBTOKEN_PART_DISTILL_LOCAL_HEADS}"
  --context-layers "${SUBTOKEN_PART_DISTILL_CONTEXT_LAYERS}"
  --context-heads "${SUBTOKEN_PART_DISTILL_CONTEXT_HEADS}"
  --global-layers "${SUBTOKEN_PART_DISTILL_GLOBAL_LAYERS}"
  --global-heads "${SUBTOKEN_PART_DISTILL_GLOBAL_HEADS}"
  --gate-mode "${SUBTOKEN_PART_DISTILL_GATE_MODE}"
  --local-pool-mode "${SUBTOKEN_PART_DISTILL_LOCAL_POOL_MODE}"
  --modality-dropout "${SUBTOKEN_PART_DISTILL_MODALITY_DROPOUT}"
  --dropout "${SUBTOKEN_PART_DISTILL_DROPOUT}"
  --attention-dropout "${SUBTOKEN_PART_DISTILL_ATTENTION_DROPOUT}"
  --anchor-source "${SUBTOKEN_PART_DISTILL_ANCHOR_SOURCE}"
)
fresh_append_optional_arg cmd --teacher-device "${SUBTOKEN_PART_DISTILL_TEACHER_DEVICE}"
fresh_append_optional_arg cmd --max-train-batches "${SUBTOKEN_PART_DISTILL_MAX_TRAIN_BATCHES}"
fresh_append_optional_arg cmd --max-val-batches "${SUBTOKEN_PART_DISTILL_MAX_VAL_BATCHES}"
fresh_append_optional_arg cmd --max-stack-val-batches "${SUBTOKEN_PART_DISTILL_MAX_STACK_VAL_BATCHES}"
fresh_append_optional_arg cmd --max-final-test-batches "${SUBTOKEN_PART_DISTILL_MAX_FINAL_TEST_BATCHES}"
fresh_append_flag_if_enabled cmd --non-strict-teacher-checkpoint "${SUBTOKEN_PART_DISTILL_NON_STRICT_TEACHER_CHECKPOINT}"
fresh_append_flag_if_enabled cmd --verify-offline-label-branches "${SUBTOKEN_PART_DISTILL_VERIFY_OFFLINE_LABEL_BRANCHES}"
fresh_append_flag_if_enabled cmd --confirm-final-test "${SUBTOKEN_PART_DISTILL_CONFIRM_FINAL_TEST}"
fresh_append_flag_if_enabled cmd --no-amp "${SUBTOKEN_PART_DISTILL_NO_AMP}"
fresh_append_flag_if_enabled cmd --compile-model "${SUBTOKEN_PART_DISTILL_COMPILE_MODEL}"
fresh_append_flag_if_enabled cmd --skip-hlt-hash-check "${SUBTOKEN_PART_DISTILL_SKIP_HLT_HASH_CHECK}"
fresh_append_flag_if_enabled cmd --disable-pairwise-bias "${SUBTOKEN_PART_DISTILL_DISABLE_PAIRWISE_BIAS}"
fresh_append_flag_if_enabled cmd --disable-particle-anchor "${SUBTOKEN_PART_DISTILL_DISABLE_PARTICLE_ANCHOR}"
fresh_append_flag_if_enabled cmd --disable-modality-type-embeddings "${SUBTOKEN_PART_DISTILL_DISABLE_MODALITY_TYPE_EMBEDDINGS}"
fresh_append_flag_if_enabled cmd --use-pt-rank-embedding "${SUBTOKEN_PART_DISTILL_USE_PT_RANK_EMBEDDING}"
fresh_append_flag_if_enabled cmd --disable-part-style-derived-features "${SUBTOKEN_PART_DISTILL_DISABLE_PART_STYLE_DERIVED_FEATURES}"

fresh_write_run_config "${SUBTOKEN_PART_DISTILL_DIR}" "subtoken_part_distill_version_b" "${cmd[@]}"
fresh_run "${cmd[@]}"

if ! fresh_is_dry_run; then
  fresh_require_file "${SUBTOKEN_PART_DISTILL_DIR}/best_model_val.pt"
  fresh_require_file "${SUBTOKEN_PART_DISTILL_DIR}/last.pt"
  fresh_require_file "${SUBTOKEN_PART_DISTILL_DIR}/training_curves.json"
  fresh_require_file "${SUBTOKEN_PART_DISTILL_DIR}/model_val_report.json"
  fresh_require_file "${SUBTOKEN_PART_DISTILL_DIR}/run_report.json"
  fresh_require_file "${SUBTOKEN_PART_DISTILL_DIR}/diagnostics/summary_metrics.csv"
fi
