#!/usr/bin/env bash
# Submit a tiny DETR/free-slot QCD-vs-Tbqq smoke test for pipeline correctness.

set -euo pipefail
IFS=$'\n\t'

: "${PROJECT_DIR:=/home/ryreu/atlas/Fresh_check}"
SCRIPT_DIR="${PROJECT_DIR}/sbatch"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

: "${UPSTREAM_DEPENDENCY:=}"
: "${TAGGER_UPSTREAM_DEPENDENCY:=}"
: "${DETR_SLOT_SMOKE_TAG:=$(date +%Y%m%d_%H%M%S)}"
: "${DETR_SLOT_SMOKE_ROOT:=${OUTPUT_ROOT}/detr_slot_smoke_${DETR_SLOT_SMOKE_TAG}}"

export DETR_SLOT_QCD_TBQQ_ROOT="${DETR_SLOT_SMOKE_ROOT}"
export DETR_SLOT_QCD_TBQQ_MODEL_TRAIN_SIZE="${DETR_SLOT_SMOKE_MODEL_TRAIN_SIZE:-10000}"
export DETR_SLOT_QCD_TBQQ_MODEL_VAL_SIZE="${DETR_SLOT_SMOKE_MODEL_VAL_SIZE:-2000}"
export DETR_SLOT_QCD_TBQQ_STACK_TRAIN_SIZE="${DETR_SLOT_SMOKE_STACK_TRAIN_SIZE:-5000}"
export DETR_SLOT_QCD_TBQQ_STACK_VAL_SIZE="${DETR_SLOT_SMOKE_STACK_VAL_SIZE:-2000}"
export DETR_SLOT_QCD_TBQQ_FINAL_TEST_SIZE="${DETR_SLOT_SMOKE_FINAL_TEST_SIZE:-10000}"
export DETR_SLOT_QCD_TBQQ_CACHE_MAX_JETS_PER_SPLIT="${DETR_SLOT_SMOKE_CACHE_MAX_JETS_PER_SPLIT:-${DETR_SLOT_QCD_TBQQ_FINAL_TEST_SIZE}}"

export DETR_SLOT_QCD_TBQQ_RECO_EPOCHS="${DETR_SLOT_SMOKE_RECO_EPOCHS:-2}"
export DETR_SLOT_QCD_TBQQ_TAGGER_EPOCHS="${DETR_SLOT_SMOKE_TAGGER_EPOCHS:-2}"
export DETR_SLOT_RECO_EARLY_STOP_PATIENCE="${DETR_SLOT_SMOKE_RECO_EARLY_STOP_PATIENCE:-1}"
export DETR_SLOT_TAGGER_EARLY_STOP_PATIENCE="${DETR_SLOT_SMOKE_TAGGER_EARLY_STOP_PATIENCE:-1}"
export DETR_SLOT_RECO_BATCH_SIZE="${DETR_SLOT_SMOKE_RECO_BATCH_SIZE:-32}"
export DETR_SLOT_CACHE_BATCH_SIZE="${DETR_SLOT_SMOKE_CACHE_BATCH_SIZE:-64}"
export DETR_SLOT_TAGGER_BATCH_SIZE="${DETR_SLOT_SMOKE_TAGGER_BATCH_SIZE:-32}"
export DETR_SLOT_EVAL_BATCH_SIZE="${DETR_SLOT_SMOKE_EVAL_BATCH_SIZE:-64}"
export DETR_SLOT_NUM_SLOTS="${DETR_SLOT_SMOKE_NUM_SLOTS:-64}"
export DETR_SLOT_EXPORT_MAX_TOKENS="${DETR_SLOT_SMOKE_EXPORT_MAX_TOKENS:-64}"
export DETR_SLOT_CACHE_EXPORT_MAX_TOKENS="${DETR_SLOT_EXPORT_MAX_TOKENS}"
export DETR_SLOT_MAX_TOKENS_PER_VIEW="${DETR_SLOT_EXPORT_MAX_TOKENS}"
export DETR_SLOT_MIN_TOKENS_PER_VIEW="${DETR_SLOT_SMOKE_MIN_TOKENS_PER_VIEW:-4}"

export DETR_SLOT_BINARY_MANIFEST_TIME="${DETR_SLOT_SMOKE_BINARY_MANIFEST_TIME:-01:00:00}"
export DETR_SLOT_BINARY_HLT_CACHE_TIME="${DETR_SLOT_SMOKE_BINARY_HLT_CACHE_TIME:-04:00:00}"
export DETR_SLOT_RECO_TIME="${DETR_SLOT_SMOKE_RECO_TIME:-04:00:00}"
export DETR_SLOT_CACHE_TIME="${DETR_SLOT_SMOKE_CACHE_TIME:-04:00:00}"
export DETR_SLOT_TAGGER_TIME="${DETR_SLOT_SMOKE_TAGGER_TIME:-04:00:00}"
export DETR_SLOT_AUDIT_TIME="${DETR_SLOT_SMOKE_AUDIT_TIME:-02:00:00}"
export DETR_SLOT_REPORT_TIME="${DETR_SLOT_SMOKE_REPORT_TIME:-01:00:00}"
export DETR_SLOT_OFFLINE_TEACHER_TIME="${DETR_SLOT_SMOKE_OFFLINE_TEACHER_TIME:-04:00:00}"

export DETR_SLOT_BINARY_MANIFEST_MEM="${DETR_SLOT_SMOKE_BINARY_MANIFEST_MEM:-8G}"
export DETR_SLOT_BINARY_HLT_CACHE_MEM="${DETR_SLOT_SMOKE_BINARY_HLT_CACHE_MEM:-48G}"
export DETR_SLOT_RECO_MEM="${DETR_SLOT_SMOKE_RECO_MEM:-48G}"
export DETR_SLOT_CACHE_MEM="${DETR_SLOT_SMOKE_CACHE_MEM:-48G}"
export DETR_SLOT_TAGGER_MEM="${DETR_SLOT_SMOKE_TAGGER_MEM:-48G}"
export DETR_SLOT_AUDIT_MEM="${DETR_SLOT_SMOKE_AUDIT_MEM:-32G}"
export DETR_SLOT_REPORT_MEM="${DETR_SLOT_SMOKE_REPORT_MEM:-8G}"
export DETR_SLOT_OFFLINE_TEACHER_MEM="${DETR_SLOT_SMOKE_OFFLINE_TEACHER_MEM:-48G}"

export DETR_SLOT_BINARY_MANIFEST_CPUS="${DETR_SLOT_SMOKE_BINARY_MANIFEST_CPUS:-2}"
export DETR_SLOT_BINARY_HLT_CACHE_CPUS="${DETR_SLOT_SMOKE_BINARY_HLT_CACHE_CPUS:-2}"
export DETR_SLOT_RECO_CPUS="${DETR_SLOT_SMOKE_RECO_CPUS:-2}"
export DETR_SLOT_CACHE_CPUS="${DETR_SLOT_SMOKE_CACHE_CPUS:-2}"
export DETR_SLOT_TAGGER_CPUS="${DETR_SLOT_SMOKE_TAGGER_CPUS:-2}"
export DETR_SLOT_AUDIT_CPUS="${DETR_SLOT_SMOKE_AUDIT_CPUS:-2}"
export DETR_SLOT_REPORT_CPUS="${DETR_SLOT_SMOKE_REPORT_CPUS:-2}"
export DETR_SLOT_OFFLINE_TEACHER_CPUS="${DETR_SLOT_SMOKE_OFFLINE_TEACHER_CPUS:-2}"

fresh_prepare_submitter
if fresh_is_dry_run; then
  echo "DRY_RUN/PRINT_ONLY enabled; delegated submitter will print sbatch commands only." >&2
fi
cat <<SUMMARY
detr_slot_smoke_submission:
  warning: smoke metrics are for pipeline correctness only, not physics interpretation
  smoke_root: ${DETR_SLOT_SMOKE_ROOT}
  smoke_sizes:
    model_train: ${DETR_SLOT_QCD_TBQQ_MODEL_TRAIN_SIZE}
    model_val: ${DETR_SLOT_QCD_TBQQ_MODEL_VAL_SIZE}
    stack_train: ${DETR_SLOT_QCD_TBQQ_STACK_TRAIN_SIZE}
    stack_val: ${DETR_SLOT_QCD_TBQQ_STACK_VAL_SIZE}
    final_test: ${DETR_SLOT_QCD_TBQQ_FINAL_TEST_SIZE}
  smoke_model:
    reco_epochs: ${DETR_SLOT_QCD_TBQQ_RECO_EPOCHS}
    tagger_epochs: ${DETR_SLOT_QCD_TBQQ_TAGGER_EPOCHS}
    num_slots: ${DETR_SLOT_NUM_SLOTS}
    export_max_tokens: ${DETR_SLOT_EXPORT_MAX_TOKENS}
SUMMARY

bash "${SCRIPT_DIR}/submit_detr_slot_qcd_tbqq_binary_experiment.sh"
