#!/usr/bin/env bash
# Queue local residual-field pilot and high-data campaigns on RIT Tigris.

set -euo pipefail
IFS=$'\n\t'

: "${PROJECT_DIR:=/home/ryreu/atlas/Fresh_check}"
: "${PD10_DATA_DIR:=/home/ryreu/atlas/PracticeTagging/data}"
: "${LOCAL_RESIDUAL_FIELD_DATA_DIR:=${PD10_DATA_DIR}}"
: "${OUTPUT_ROOT:=${PROJECT_DIR}/checkpoints}"
: "${CONDA_ENV:=atlas_kd_tigris}"
: "${CONDA_BASE:=/home/ryreu/miniforge3-aarch64}"
: "${DEVICE:=cuda}"
: "${SKIP_EXISTING:=0}"
: "${OVERWRITE:=0}"
: "${LOCAL_RESIDUAL_FIELD_SBATCH_ACCOUNT:=}"
: "${LOCAL_RESIDUAL_FIELD_SBATCH_PARTITION:=tigris}"
: "${LOCAL_RESIDUAL_FIELD_GPU_GRES:=gpu:gh200:1}"
: "${LOCAL_RESIDUAL_FIELD_GPU_CPUS_PER_TASK:=16}"
: "${LOCAL_RESIDUAL_FIELD_GPU_MEM:=220G}"
: "${LOCAL_RESIDUAL_FIELD_CPU_CPUS_PER_TASK:=16}"
: "${LOCAL_RESIDUAL_FIELD_CPU_MEM:=300G}"
: "${CONFIRM_FINAL_TEST:=1}"

unset LOCAL_RESIDUAL_FIELD_ROOT

export PROJECT_DIR PD10_DATA_DIR LOCAL_RESIDUAL_FIELD_DATA_DIR OUTPUT_ROOT
export CONDA_ENV CONDA_BASE DEVICE SKIP_EXISTING OVERWRITE
export LOCAL_RESIDUAL_FIELD_SBATCH_ACCOUNT LOCAL_RESIDUAL_FIELD_SBATCH_PARTITION LOCAL_RESIDUAL_FIELD_GPU_GRES
export LOCAL_RESIDUAL_FIELD_GPU_CPUS_PER_TASK LOCAL_RESIDUAL_FIELD_GPU_MEM
export LOCAL_RESIDUAL_FIELD_CPU_CPUS_PER_TASK LOCAL_RESIDUAL_FIELD_CPU_MEM
export CONFIRM_FINAL_TEST

LOCAL_RESIDUAL_FIELD_CAMPAIGN_MODE=pilot bash "${PROJECT_DIR}/sbatch/submit_local_particle_residual_field_experiment.sh"
LOCAL_RESIDUAL_FIELD_CAMPAIGN_MODE=highdata bash "${PROJECT_DIR}/sbatch/submit_local_particle_residual_field_experiment.sh"
