#!/usr/bin/env bash
# Submit both AV10 10-class ablation pilot and high-data campaigns.

set -euo pipefail
IFS=$'\n\t'

: "${PROJECT_DIR:=/home/ryreu/atlas/Fresh_check}"
: "${CONDA_ENV:=atlas_kd}"
export CONDA_ENV
SCRIPT_DIR="${PROJECT_DIR}/sbatch"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"
SUBMIT_SCRIPT="${SCRIPT_DIR}/submit_architecture_view_10class_ablation_experiment.sh"

: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_RUN_STAMP:=$(date +%Y%m%d_%H%M%S)}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_SUBMIT_PILOT:=1}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_SUBMIT_HIGHDATA:=1}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_AFTER_PILOT:=0}"

: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_TAG:=pilot_${ARCHITECTURE_VIEW_10CLASS_ABLATION_RUN_STAMP}}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_MODEL_TRAIN_SIZE:=500000}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_MODEL_VAL_SIZE:=150000}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_STACK_TRAIN_SIZE:=500000}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_STACK_VAL_SIZE:=150000}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_FINAL_TEST_SIZE:=500000}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_TRAIN_TIME:=3-00:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_STANDALONE_TIME:=2-00:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_CACHE_TIME:=1-00:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_PREDICTION_TIME:=1-00:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_FUSION_TIME:=06:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_OFFLINE_CACHE_TIME:=1-00:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_REUSE_EXISTING_INPUTS:=0}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_EXISTING_INPUT_ROOT:=}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_EXISTING_MANIFEST_PATH:=}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_EXISTING_HLT_CACHE_DIR:=}"

: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_TAG:=highdata_${ARCHITECTURE_VIEW_10CLASS_ABLATION_RUN_STAMP}}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_MODEL_TRAIN_SIZE:=3000000}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_MODEL_VAL_SIZE:=1000000}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_STACK_TRAIN_SIZE:=3000000}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_STACK_VAL_SIZE:=1000000}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_FINAL_TEST_SIZE:=1000000}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_TRAIN_TIME:=5-00:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_STANDALONE_TIME:=3-00:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_CACHE_TIME:=1-12:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_PREDICTION_TIME:=1-12:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_FUSION_TIME:=08:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_OFFLINE_CACHE_TIME:=1-12:00:00}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_REUSE_EXISTING_INPUTS:=0}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_EXISTING_INPUT_ROOT:=}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_EXISTING_MANIFEST_PATH:=}"
: "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_EXISTING_HLT_CACHE_DIR:=}"

require_file() {
  local path="$1"
  if [[ ! -f "${path}" ]]; then
    echo "required file is missing: ${path}" >&2
    exit 1
  fi
}

fresh_prepare_submitter
echo "wrapper_dry_run=$(fresh_is_dry_run && echo 1 || echo 0)"

submit_campaign() {
  local label="$1"
  local tag="$2"
  local train_size="$3"
  local val_size="$4"
  local stack_train_size="$5"
  local stack_val_size="$6"
  local final_test_size="$7"
  local train_time="$8"
  local standalone_time="$9"
  local cache_time="${10}"
  local prediction_time="${11}"
  local fusion_time="${12}"
  local offline_cache_time="${13}"
  local reuse_existing_inputs="${14}"
  local existing_input_root="${15}"
  local existing_manifest_path="${16}"
  local existing_hlt_cache_dir="${17}"
  local dependency="${18:-}"

  require_file "${SUBMIT_SCRIPT}"
  echo "submitting ${label}:"
  echo "  tag=${tag}"
  echo "  sizes=${train_size}/${val_size}/${stack_train_size}/${stack_val_size}/${final_test_size}"
  echo "  reuse_existing_inputs=${reuse_existing_inputs}"
  echo "  existing_input_root=${existing_input_root:-none}"
  echo "  upstream_dependency=${dependency:-none}"

  UPSTREAM_DEPENDENCY="${dependency}" \
  ARCHITECTURE_VIEW_10CLASS_ABLATION_TAG="${tag}" \
  ARCHITECTURE_VIEW_10CLASS_REUSE_EXISTING_INPUTS="${reuse_existing_inputs}" \
  ARCHITECTURE_VIEW_10CLASS_EXISTING_INPUT_ROOT="${existing_input_root}" \
  ARCHITECTURE_VIEW_10CLASS_EXISTING_MANIFEST_PATH="${existing_manifest_path}" \
  ARCHITECTURE_VIEW_10CLASS_EXISTING_HLT_CACHE_DIR="${existing_hlt_cache_dir}" \
  ARCHITECTURE_VIEW_10CLASS_MODEL_TRAIN_SIZE="${train_size}" \
  ARCHITECTURE_VIEW_10CLASS_MODEL_VAL_SIZE="${val_size}" \
  ARCHITECTURE_VIEW_10CLASS_STACK_TRAIN_SIZE="${stack_train_size}" \
  ARCHITECTURE_VIEW_10CLASS_STACK_VAL_SIZE="${stack_val_size}" \
  ARCHITECTURE_VIEW_10CLASS_FINAL_TEST_SIZE="${final_test_size}" \
  ARCHITECTURE_VIEW_10CLASS_TRAIN_TIME="${train_time}" \
  ARCHITECTURE_VIEW_10CLASS_OFFLINE_TRAIN_TIME="${train_time}" \
  ARCHITECTURE_VIEW_10CLASS_STANDALONE_TIME="${standalone_time}" \
  ARCHITECTURE_VIEW_10CLASS_CACHE_TIME="${cache_time}" \
  ARCHITECTURE_VIEW_10CLASS_OFFLINE_CACHE_TIME="${offline_cache_time}" \
  ARCHITECTURE_VIEW_10CLASS_PREDICTION_TIME="${prediction_time}" \
  ARCHITECTURE_VIEW_10CLASS_FUSION_TIME="${fusion_time}" \
  bash "${SUBMIT_SCRIPT}"
}

pilot_report_job=""
if [[ "${ARCHITECTURE_VIEW_10CLASS_ABLATION_SUBMIT_PILOT}" == "1" ]]; then
  pilot_output="$(submit_campaign \
    "AV10 ablation 500k pilot" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_TAG}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_MODEL_TRAIN_SIZE}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_MODEL_VAL_SIZE}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_STACK_TRAIN_SIZE}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_STACK_VAL_SIZE}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_FINAL_TEST_SIZE}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_TRAIN_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_STANDALONE_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_CACHE_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_PREDICTION_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_FUSION_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_OFFLINE_CACHE_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_REUSE_EXISTING_INPUTS}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_EXISTING_INPUT_ROOT}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_EXISTING_MANIFEST_PATH}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_PILOT_EXISTING_HLT_CACHE_DIR}")"
  echo "${pilot_output}"
  pilot_report_job="$(echo "${pilot_output}" | awk -F': ' '/^[[:space:]]+ablation_report:/ {print $2; exit}')"
fi

high_dependency=""
if [[ "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_AFTER_PILOT}" == "1" && -n "${pilot_report_job}" ]]; then
  high_dependency="${pilot_report_job}"
fi

if [[ "${ARCHITECTURE_VIEW_10CLASS_ABLATION_SUBMIT_HIGHDATA}" == "1" ]]; then
  submit_campaign \
    "AV10 ablation high-data" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_TAG}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_MODEL_TRAIN_SIZE}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_MODEL_VAL_SIZE}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_STACK_TRAIN_SIZE}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_STACK_VAL_SIZE}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_FINAL_TEST_SIZE}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_TRAIN_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_STANDALONE_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_CACHE_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_PREDICTION_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_FUSION_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_OFFLINE_CACHE_TIME}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_REUSE_EXISTING_INPUTS}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_EXISTING_INPUT_ROOT}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_EXISTING_MANIFEST_PATH}" \
    "${ARCHITECTURE_VIEW_10CLASS_ABLATION_HIGHDATA_EXISTING_HLT_CACHE_DIR}" \
    "${high_dependency}"
fi
