#!/usr/bin/env bash
# Submit the Step 10 first serious QCD-vs-Hgg local-graph comparison.

set -euo pipefail
IFS=$'\n\t'

: "${PROJECT_DIR:=/home/ryreu/atlas/Fresh_check}"
SCRIPT_DIR="${PROJECT_DIR}/sbatch"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

: "${LOCAL_GRAPH_PART_STEP10_TAG:=$(date +%Y%m%d_%H%M%S)}"
: "${LOCAL_GRAPH_PART_STEP10_HLT_DEGRADATION_STRENGTH:=0.6}"
LOCAL_GRAPH_PART_STEP10_HLT_TAG="${LOCAL_GRAPH_PART_STEP10_HLT_DEGRADATION_STRENGTH//./p}"
: "${LOCAL_GRAPH_PART_STEP10_ROOT:=${OUTPUT_ROOT}/local_graph_part_step10_qcd_hgg_binary_hlt${LOCAL_GRAPH_PART_STEP10_HLT_TAG}_${LOCAL_GRAPH_PART_STEP10_TAG}}"

export LOCAL_GRAPH_PART_QCD_HGG_ROOT="${LOCAL_GRAPH_PART_STEP10_ROOT}"
export LOCAL_GRAPH_PART_QCD_HGG_HLT_DEGRADATION_STRENGTH="${LOCAL_GRAPH_PART_STEP10_HLT_DEGRADATION_STRENGTH}"
export HLT_DEGRADATION_STRENGTH="${LOCAL_GRAPH_PART_STEP10_HLT_DEGRADATION_STRENGTH}"

export LOCAL_GRAPH_PART_QCD_HGG_VARIANTS="${LOCAL_GRAPH_PART_STEP10_VARIANTS:-hlt_part_baseline local_edgeconv_adapter local_point_attention_adapter local_point_attention_adapter_warmstart}"
export LOCAL_GRAPH_PART_QCD_HGG_MODEL_TRAIN_SIZE="${LOCAL_GRAPH_PART_STEP10_MODEL_TRAIN_SIZE:-500000}"
export LOCAL_GRAPH_PART_QCD_HGG_MODEL_VAL_SIZE="${LOCAL_GRAPH_PART_STEP10_MODEL_VAL_SIZE:-150000}"
export LOCAL_GRAPH_PART_QCD_HGG_STACK_TRAIN_SIZE="${LOCAL_GRAPH_PART_STEP10_STACK_TRAIN_SIZE:-500000}"
export LOCAL_GRAPH_PART_QCD_HGG_STACK_VAL_SIZE="${LOCAL_GRAPH_PART_STEP10_STACK_VAL_SIZE:-150000}"
export LOCAL_GRAPH_PART_QCD_HGG_FINAL_TEST_SIZE="${LOCAL_GRAPH_PART_STEP10_FINAL_TEST_SIZE:-500000}"
export LOCAL_GRAPH_PART_QCD_HGG_EPOCHS="${LOCAL_GRAPH_PART_STEP10_EPOCHS:-45}"
export LOCAL_GRAPH_PART_QCD_HGG_SELECTION_METRIC="${LOCAL_GRAPH_PART_STEP10_SELECTION_METRIC:-fpr_at_signal_eff_0p50}"
export LOCAL_GRAPH_PART_QCD_HGG_K="${LOCAL_GRAPH_PART_STEP10_K:-16}"
export LOCAL_GRAPH_PART_QCD_HGG_WARM_START_FREEZE_EPOCHS="${LOCAL_GRAPH_PART_STEP10_WARM_START_FREEZE_EPOCHS:-0}"
export LOCAL_GRAPH_PART_QCD_HGG_WARM_START_RESIDUAL_GAMMA_INIT="${LOCAL_GRAPH_PART_STEP10_WARM_START_RESIDUAL_GAMMA_INIT:-0.01}"

export LOCAL_GRAPH_PART_QCD_HGG_BUILD_BINARY_INPUTS="${LOCAL_GRAPH_PART_STEP10_BUILD_BINARY_INPUTS:-1}"
export LOCAL_GRAPH_PART_QCD_HGG_BUILD_DIRECT_BINARY_SPLITS="${LOCAL_GRAPH_PART_STEP10_BUILD_DIRECT_BINARY_SPLITS:-1}"
export LOCAL_GRAPH_PART_QCD_HGG_BINARY_MANIFEST_MEM="${LOCAL_GRAPH_PART_STEP10_BINARY_MANIFEST_MEM:-16G}"
export LOCAL_GRAPH_PART_QCD_HGG_BINARY_HLT_CACHE_MEM="${LOCAL_GRAPH_PART_STEP10_BINARY_HLT_CACHE_MEM:-128G}"
export LOCAL_GRAPH_PART_QCD_HGG_TRAIN_MEM="${LOCAL_GRAPH_PART_STEP10_TRAIN_MEM:-160G}"
export LOCAL_GRAPH_PART_QCD_HGG_REPORT_MEM="${LOCAL_GRAPH_PART_STEP10_REPORT_MEM:-8G}"
export LOCAL_GRAPH_PART_QCD_HGG_BINARY_MANIFEST_TIME="${LOCAL_GRAPH_PART_STEP10_BINARY_MANIFEST_TIME:-04:00:00}"
export LOCAL_GRAPH_PART_QCD_HGG_BINARY_HLT_CACHE_TIME="${LOCAL_GRAPH_PART_STEP10_BINARY_HLT_CACHE_TIME:-1-00:00:00}"
export LOCAL_GRAPH_PART_QCD_HGG_TRAIN_TIME="${LOCAL_GRAPH_PART_STEP10_TRAIN_TIME:-2-12:00:00}"
export LOCAL_GRAPH_PART_QCD_HGG_REPORT_TIME="${LOCAL_GRAPH_PART_STEP10_REPORT_TIME:-02:00:00}"
export LOCAL_GRAPH_PART_QCD_HGG_BINARY_MANIFEST_CPUS="${LOCAL_GRAPH_PART_STEP10_BINARY_MANIFEST_CPUS:-2}"
export LOCAL_GRAPH_PART_QCD_HGG_BINARY_HLT_CACHE_CPUS="${LOCAL_GRAPH_PART_STEP10_BINARY_HLT_CACHE_CPUS:-4}"
export LOCAL_GRAPH_PART_QCD_HGG_TRAIN_CPUS="${LOCAL_GRAPH_PART_STEP10_TRAIN_CPUS:-8}"
export LOCAL_GRAPH_PART_QCD_HGG_REPORT_CPUS="${LOCAL_GRAPH_PART_STEP10_REPORT_CPUS:-2}"

fresh_prepare_submitter
if fresh_is_dry_run; then
  echo "DRY_RUN/PRINT_ONLY enabled; delegated submitter will print sbatch commands only." >&2
fi

cat <<SUMMARY
local_graph_part_step10_first_serious_run:
  task: QCD_vs_Hgg_local_graph_part_step10
  root: ${LOCAL_GRAPH_PART_QCD_HGG_ROOT}
  hlt_degradation_strength: ${LOCAL_GRAPH_PART_QCD_HGG_HLT_DEGRADATION_STRENGTH}
  split_caps:
    model_train: ${LOCAL_GRAPH_PART_QCD_HGG_MODEL_TRAIN_SIZE}
    model_val: ${LOCAL_GRAPH_PART_QCD_HGG_MODEL_VAL_SIZE}
    stack_train: ${LOCAL_GRAPH_PART_QCD_HGG_STACK_TRAIN_SIZE}
    stack_val: ${LOCAL_GRAPH_PART_QCD_HGG_STACK_VAL_SIZE}
    final_test: ${LOCAL_GRAPH_PART_QCD_HGG_FINAL_TEST_SIZE}
  model:
    variants: ${LOCAL_GRAPH_PART_QCD_HGG_VARIANTS}
    epochs: ${LOCAL_GRAPH_PART_QCD_HGG_EPOCHS}
    selection_metric: ${LOCAL_GRAPH_PART_QCD_HGG_SELECTION_METRIC}
    k: ${LOCAL_GRAPH_PART_QCD_HGG_K}
    warm_start_freeze_epochs: ${LOCAL_GRAPH_PART_QCD_HGG_WARM_START_FREEZE_EPOCHS}
    warm_start_residual_gamma_init: ${LOCAL_GRAPH_PART_QCD_HGG_WARM_START_RESIDUAL_GAMMA_INIT}
  resources:
    binary_manifest: time=${LOCAL_GRAPH_PART_QCD_HGG_BINARY_MANIFEST_TIME} mem=${LOCAL_GRAPH_PART_QCD_HGG_BINARY_MANIFEST_MEM} cpus=${LOCAL_GRAPH_PART_QCD_HGG_BINARY_MANIFEST_CPUS}
    binary_hlt_cache: time=${LOCAL_GRAPH_PART_QCD_HGG_BINARY_HLT_CACHE_TIME} mem=${LOCAL_GRAPH_PART_QCD_HGG_BINARY_HLT_CACHE_MEM} cpus=${LOCAL_GRAPH_PART_QCD_HGG_BINARY_HLT_CACHE_CPUS}
    train: time=${LOCAL_GRAPH_PART_QCD_HGG_TRAIN_TIME} mem=${LOCAL_GRAPH_PART_QCD_HGG_TRAIN_MEM} cpus=${LOCAL_GRAPH_PART_QCD_HGG_TRAIN_CPUS}
    report: time=${LOCAL_GRAPH_PART_QCD_HGG_REPORT_TIME} mem=${LOCAL_GRAPH_PART_QCD_HGG_REPORT_MEM} cpus=${LOCAL_GRAPH_PART_QCD_HGG_REPORT_CPUS}
SUMMARY

bash "${SCRIPT_DIR}/submit_local_graph_qcd_hgg_binary_experiment.sh"
