"""Teacher-logit reconstruction research interfaces.

This package is intentionally separate from the earlier ``jetclass_fresh``
reconstructor line.  The first implemented pieces are shared data/view
interfaces and frozen teacher adapters; reconstructor and loss implementations
arrive in later steps.
"""

from .views import (
    PairedJetViews,
    SoftReconstructedView,
    limit_split_manifest,
    load_paired_jet_views,
    make_identity_soft_view,
    make_soft_view_from_parents_and_extras,
    soft_view_to_particle_transformer_inputs,
    summarize_paired_jet_views,
    summarize_soft_view,
    validate_view_alignment,
)
from .teachers import (
    FrozenTeacher,
    FrozenTeacherMetadata,
    TEACHER_ARCHITECTURES,
    assert_teacher_frozen,
    build_teacher_model_from_payload,
    infer_teacher_architecture,
    load_frozen_teacher,
    normalize_teacher_architecture,
    summarize_teacher_forward,
)
from .global_transformer import (
    GlobalTransformerReconstructor,
    GlobalTransformerReconstructorConfig,
    build_global_transformer_reconstructor,
    jet_axes_from_tokens,
    physical_energy_floor,
    sanitize_hlt_tokens,
    token_embedding_features,
)
from .reconstructor_builders import (
    TEACHER_LOGIT_RECONSTRUCTOR_ARCHITECTURES,
    build_teacher_logit_reconstructor,
    infer_reconstructor_architecture_from_payload,
    load_teacher_logit_reconstructor_checkpoint,
    normalize_reconstructor_architecture,
)
from .losses import (
    TeacherLogitRecoLossConfig,
    TeacherLogitRecoLossOutput,
    compute_teacher_logit_reco_loss,
    correction_budget_loss,
    global_transformer_teacher_training_step,
    teacher_cross_entropy_loss,
    teacher_kl_loss,
    weak_jet_summary_loss,
    weighted_jet_summary,
)
from .train_global_transformer import (
    EXPERIMENT_STEP as TEACHER_LOGIT_GT_TRAIN_EXPERIMENT_STEP,
    PairedTeacherLogitDataset,
    TeacherLogitGlobalTransformerTrainConfig,
    collate_paired_teacher_logit,
    make_teacher_logit_loader,
    run_teacher_logit_reco_epoch,
    source_metadata,
    train_teacher_logit_global_transformer_reco,
)
from .predict_global_transformer import (
    PREDICT_EXPERIMENT_STEP as TEACHER_LOGIT_GT_PREDICT_EXPERIMENT_STEP,
    HLTPredictionDataset,
    TeacherLogitGlobalTransformerPredictionConfig,
    collect_teacher_logit_global_transformer_predictions,
    default_model_name_for_teacher_architecture,
    evaluate_teacher_logit_reco_model,
    load_global_transformer_reconstructor_checkpoint,
    teacher_architecture_from_payload,
    teacher_checkpoint_from_payload,
)

__all__ = [
    "PairedJetViews",
    "SoftReconstructedView",
    "limit_split_manifest",
    "load_paired_jet_views",
    "make_identity_soft_view",
    "make_soft_view_from_parents_and_extras",
    "soft_view_to_particle_transformer_inputs",
    "summarize_paired_jet_views",
    "summarize_soft_view",
    "validate_view_alignment",
    "FrozenTeacher",
    "FrozenTeacherMetadata",
    "TEACHER_ARCHITECTURES",
    "assert_teacher_frozen",
    "build_teacher_model_from_payload",
    "infer_teacher_architecture",
    "load_frozen_teacher",
    "normalize_teacher_architecture",
    "summarize_teacher_forward",
    "GlobalTransformerReconstructor",
    "GlobalTransformerReconstructorConfig",
    "build_global_transformer_reconstructor",
    "jet_axes_from_tokens",
    "physical_energy_floor",
    "sanitize_hlt_tokens",
    "token_embedding_features",
    "TEACHER_LOGIT_RECONSTRUCTOR_ARCHITECTURES",
    "build_teacher_logit_reconstructor",
    "infer_reconstructor_architecture_from_payload",
    "load_teacher_logit_reconstructor_checkpoint",
    "normalize_reconstructor_architecture",
    "TeacherLogitRecoLossConfig",
    "TeacherLogitRecoLossOutput",
    "compute_teacher_logit_reco_loss",
    "correction_budget_loss",
    "global_transformer_teacher_training_step",
    "teacher_cross_entropy_loss",
    "teacher_kl_loss",
    "weak_jet_summary_loss",
    "weighted_jet_summary",
    "TEACHER_LOGIT_GT_TRAIN_EXPERIMENT_STEP",
    "PairedTeacherLogitDataset",
    "TeacherLogitGlobalTransformerTrainConfig",
    "collate_paired_teacher_logit",
    "make_teacher_logit_loader",
    "run_teacher_logit_reco_epoch",
    "source_metadata",
    "train_teacher_logit_global_transformer_reco",
    "TEACHER_LOGIT_GT_PREDICT_EXPERIMENT_STEP",
    "HLTPredictionDataset",
    "TeacherLogitGlobalTransformerPredictionConfig",
    "collect_teacher_logit_global_transformer_predictions",
    "default_model_name_for_teacher_architecture",
    "evaluate_teacher_logit_reco_model",
    "load_global_transformer_reconstructor_checkpoint",
    "teacher_architecture_from_payload",
    "teacher_checkpoint_from_payload",
]
