"""Teacher-logit reconstruction research interfaces.

This package is intentionally separate from the earlier ``jetclass_fresh``
reconstructor line.  The first implemented pieces are shared data/view
interfaces and frozen teacher adapters; reconstructor and loss implementations
arrive in later steps.
"""

from .views import (
    PairedJetViews,
    SoftReconstructedView,
    limit_split_manifest,
    load_paired_jet_views,
    make_identity_soft_view,
    make_soft_view_from_parents_and_extras,
    soft_view_to_particle_transformer_inputs,
    summarize_paired_jet_views,
    summarize_soft_view,
    validate_view_alignment,
)
from .teachers import (
    FrozenTeacher,
    FrozenTeacherMetadata,
    TEACHER_ARCHITECTURES,
    assert_teacher_frozen,
    build_teacher_model_from_payload,
    infer_teacher_architecture,
    load_frozen_teacher,
    normalize_teacher_architecture,
    summarize_teacher_forward,
)
from .global_transformer import (
    GlobalTransformerReconstructor,
    GlobalTransformerReconstructorConfig,
    build_global_transformer_reconstructor,
    jet_axes_from_tokens,
    physical_energy_floor,
    sanitize_hlt_tokens,
    token_embedding_features,
)
from .reconstructor_builders import (
    TEACHER_LOGIT_RECONSTRUCTOR_ARCHITECTURES,
    build_reconstructor_from_config,
    build_teacher_logit_reconstructor,
    infer_reconstructor_architecture_from_payload,
    load_teacher_logit_reconstructor_checkpoint,
    normalize_reconstructor_architecture,
)
from .crossarch_experiment import (
    DEFAULT_FUSERS as CROSSARCH_DEFAULT_FUSERS,
    DIRECT_HLT_ARCHITECTURES as CROSSARCH_DIRECT_HLT_ARCHITECTURES,
    EXPERIMENT_NAME as CROSSARCH_EXPERIMENT_NAME,
    EXPERIMENT_STEP as CROSSARCH_EXPERIMENT_STEP,
    MIXED4_RECO_TEACHER_PAIRS as CROSSARCH_MIXED4_RECO_TEACHER_PAIRS,
    RECONSTRUCTOR_ARCHITECTURES as CROSSARCH_RECONSTRUCTOR_ARCHITECTURES,
    RECONSTRUCTOR_IMPLEMENTATIONS as CROSSARCH_RECONSTRUCTOR_IMPLEMENTATIONS,
    REQUIRED_FUSION_GROUPS as CROSSARCH_REQUIRED_FUSION_GROUPS,
    SAME_FAMILY_RECO_TEACHER_PAIRS as CROSSARCH_SAME_FAMILY_RECO_TEACHER_PAIRS,
    SPLIT_ORDER as CROSSARCH_SPLIT_ORDER,
    SPLIT_SIZES as CROSSARCH_SPLIT_SIZES,
    TEACHER_ARCHITECTURES as CROSSARCH_TEACHER_ARCHITECTURES,
    CrossArchExperimentConfig,
    CrossArchExperimentLayout,
    CrossArchSourceSpec,
    FusionGroupSpec,
    build_fusion_groups as build_crossarch_fusion_groups,
    build_hlt_source_specs as build_crossarch_hlt_source_specs,
    build_reco_source_specs as build_crossarch_reco_source_specs,
    default_crossarch_experiment_config,
    hlt_model_name as crossarch_hlt_model_name,
    normalize_reconstructor_architecture as normalize_crossarch_reconstructor_architecture,
    normalize_teacher_architecture as normalize_crossarch_teacher_architecture,
    reco_model_name as crossarch_reco_model_name,
    validate_fusion_groups as validate_crossarch_fusion_groups,
)
from .crossarch_offline_teachers import (
    EXPERIMENT_STEP as CROSSARCH_OFFLINE_TEACHER_EXPERIMENT_STEP,
    REGISTER_EXPERIMENT_STEP as CROSSARCH_OFFLINE_TEACHER_REGISTER_EXPERIMENT_STEP,
    TRAIN_EXPERIMENT_STEP as CROSSARCH_OFFLINE_TEACHER_TRAIN_EXPERIMENT_STEP,
    CrossArchOfflineTeacherTrainConfig,
    crossarch_offline_teacher_dir,
    maybe_load_checkpoint_metadata,
    normalize_crossarch_teacher_architecture as normalize_crossarch_offline_teacher_architecture,
    register_crossarch_offline_teacher_checkpoint,
    sha256_file,
    train_crossarch_offline_teacher,
)
from .crossarch_hlt_baselines import (
    EXPERIMENT_STEP as CROSSARCH_HLT_BASELINE_EXPERIMENT_STEP,
    PREDICT_EXPERIMENT_STEP as CROSSARCH_HLT_BASELINE_PREDICT_EXPERIMENT_STEP,
    PREDICTION_SPLITS as CROSSARCH_HLT_BASELINE_PREDICTION_SPLITS,
    TRAIN_EXPERIMENT_STEP as CROSSARCH_HLT_BASELINE_TRAIN_EXPERIMENT_STEP,
    CrossArchHLTBaselinePredictionConfig,
    CrossArchHLTBaselineTrainConfig,
    collect_crossarch_hlt_baseline_predictions,
    crossarch_hlt_baseline_dir,
    crossarch_hlt_checkpoint_path,
    normalize_crossarch_hlt_architecture,
    split_size_for_crossarch_hlt_prediction,
    train_crossarch_hlt_baseline,
)
from .crossarch_reconstructors import (
    EXPERIMENT_STEP as CROSSARCH_RECONSTRUCTOR_EXPERIMENT_STEP,
    RECONSTRUCTOR_TRAIN_SCRIPTS as CROSSARCH_RECONSTRUCTOR_TRAIN_SCRIPTS,
    TRAIN_EXPERIMENT_STEP as CROSSARCH_RECONSTRUCTOR_TRAIN_EXPERIMENT_STEP,
    CrossArchReconstructorSpec,
    build_crossarch_reconstructor_spec,
    build_crossarch_reconstructor_specs,
    crossarch_reconstructor_checkpoint,
    crossarch_reconstructor_dir,
    crossarch_reconstructor_model_name as crossarch_step5_reconstructor_model_name,
    crossarch_teacher_checkpoint_path,
    train_script_for_reconstructor,
)
from .crossarch_predictions import (
    EXPERIMENT_STEP as CROSSARCH_PREDICTION_EXPERIMENT_STEP,
    HLT_PREDICT_EXPERIMENT_STEP as CROSSARCH_HLT_PREDICTION_EXPERIMENT_STEP,
    HLT_PREDICT_SCRIPT as CROSSARCH_HLT_PREDICT_SCRIPT,
    RECONSTRUCTOR_PREDICT_SCRIPTS as CROSSARCH_RECONSTRUCTOR_PREDICT_SCRIPTS,
    RECO_PREDICT_EXPERIMENT_STEP as CROSSARCH_RECO_PREDICTION_EXPERIMENT_STEP,
    CrossArchPredictionSpec,
    build_crossarch_hlt_prediction_specs,
    build_crossarch_prediction_specs,
    build_crossarch_reco_prediction_specs,
    crossarch_hlt_prediction_spec,
    crossarch_reco_prediction_spec,
    predict_script_for_reconstructor,
)
from .crossarch_fusion import (
    ALL_FEATURE_MODES as CROSSARCH_ALL_FEATURE_MODES,
    BIN_GATED_FUSER_FEATURE_MODE as CROSSARCH_BIN_GATED_FUSER_FEATURE_MODE,
    CONTROL_WARNING_CHANCE_MARGIN as CROSSARCH_CONTROL_WARNING_CHANCE_MARGIN,
    CONTROL_WARNING_MIN_ACCURACY as CROSSARCH_CONTROL_WARNING_MIN_ACCURACY,
    DEFAULT_BIN_SCORE_NAMES as CROSSARCH_DEFAULT_BIN_SCORE_NAMES,
    DEFAULT_CONTROL_FEATURE_MODES as CROSSARCH_DEFAULT_CONTROL_FEATURE_MODES,
    DEFAULT_CROSSARCH_FUSERS as CROSSARCH_DEFAULT_STEP8_FUSERS,
    EXPERIMENT_STEP as CROSSARCH_FUSION_FEATURE_EXPERIMENT_STEP,
    FEATURE_MODES as CROSSARCH_FUSION_FEATURE_MODES,
    FUSER_EXPERIMENT_STEP as CROSSARCH_FUSER_EXPERIMENT_STEP,
    LOGITS_PROBS_UNCERTAINTY_FEATURE_MODE as CROSSARCH_LOGITS_PROBS_UNCERTAINTY_FEATURE_MODE,
    LOGISTIC_FUSER_FEATURE_MODES as CROSSARCH_LOGISTIC_FUSER_FEATURE_MODES,
    UNCERTAINTY_FEATURE_MODE as CROSSARCH_UNCERTAINTY_FEATURE_MODE,
    CrossArchFusionFeatureBuildConfig,
    CrossArchFusionFitConfig,
    CrossArchSplitFeatureSet,
    NamedFeatureMatrix,
    assign_bins_from_specs,
    assign_quantile_bins,
    audit_group_prediction_blocks,
    bin_assignment_name_for_fuser,
    build_bin_scores,
    build_group_feature_report,
    build_split_feature_set,
    build_split_feature_set_from_blocks,
    build_uncertainty_feature_matrix,
    default_crossarch_feature_groups,
    distinct_predicted_class_count,
    entropy_from_probs,
    evaluate_mean_fuser,
    fit_bin_gated_logistic_fuser,
    fit_bin_specs,
    fit_global_logistic_fuser,
    fit_group_fusers,
    final_test_guardrail_audit,
    labels_hash as crossarch_fusion_labels_hash,
    load_group_fusion_data,
    mean_logits_probs,
    mean_probs_probs,
    pairwise_disagreement_fraction,
    predicted_classes,
    quantile_edges,
    raw_feature_matrix,
    run_crossarch_feature_builder,
    run_crossarch_fusers,
    run_group_negative_controls,
    save_feature_set,
    top1_margin_from_probs,
    validate_crossarch_feature_groups,
)
from .particle_flow_reconstructor import (
    PARTICLE_FLOW_FEATURE_NAMES,
    PARTICLE_FLOW_INPUT_FEATURE_DIM,
    PARTICLE_FLOW_RECONSTRUCTOR_ARCHITECTURE,
    PARTICLE_FLOW_SUMMARY_FEATURE_NAMES,
    PARTICLE_FLOW_SUMMARY_FEATURE_DIM,
    ParticleFlowContextBuilder,
    ParticleFlowEncoder,
    ParticleFlowEncoderOutput,
    ParticleFlowReconstructor,
    ParticleFlowReconstructorConfig,
    build_particle_flow_reconstructor,
    build_particle_flow_features,
    build_particle_flow_summary_features,
    masked_max_pool,
    masked_mean_pool,
    masked_sum_pool,
)
from .particle_cnn_reconstructor import (
    PARTICLE_CNN_BASE_FEATURE_NAMES,
    PARTICLE_CNN_FEATURE_NAMES,
    PARTICLE_CNN_INPUT_FEATURE_DIM,
    PARTICLE_CNN_ORDERING_ASSUMPTION,
    PARTICLE_CNN_RANK_FEATURE_NAMES,
    PARTICLE_CNN_RECONSTRUCTOR_ARCHITECTURE,
    ParticleCnnBlock,
    ParticleCnnContextBuilder,
    ParticleCnnEncoder,
    ParticleCnnEncoderOutput,
    ParticleCnnReconstructor,
    ParticleCnnReconstructorConfig,
    apply_particle_mask_channels,
    audit_particle_cnn_cache_order,
    build_particle_cnn_features,
    build_particle_cnn_reconstructor,
    build_rank_features,
    masked_max_pool as particle_cnn_masked_max_pool,
    masked_mean_pool as particle_cnn_masked_mean_pool,
    masked_sum_pool as particle_cnn_masked_sum_pool,
)
from .particle_net_reconstructor import (
    EdgeConvBlock,
    PARTICLE_NET_INPUT_FEATURE_DIM,
    PARTICLE_NET_KNN_COORD_DIM,
    ParticleNetReconstructor,
    ParticleNetReconstructorConfig,
    ParticleNetEncoder,
    build_particle_net_reconstructor,
    gather_neighbor_features,
    masked_knn_indices,
    particle_net_input_features,
    particle_net_knn_coordinates,
)
from .losses import (
    TeacherLogitRecoLossConfig,
    TeacherLogitRecoLossOutput,
    compute_teacher_logit_reco_loss,
    correction_budget_loss,
    global_transformer_teacher_training_step,
    teacher_cross_entropy_loss,
    teacher_kl_loss,
    weak_jet_summary_loss,
    weighted_jet_summary,
)
from .train_global_transformer import (
    EXPERIMENT_STEP as TEACHER_LOGIT_GT_TRAIN_EXPERIMENT_STEP,
    PairedTeacherLogitDataset,
    TeacherLogitGlobalTransformerTrainConfig,
    collate_paired_teacher_logit,
    make_teacher_logit_loader,
    run_teacher_logit_reco_epoch,
    source_metadata,
    train_teacher_logit_global_transformer_reco,
)
from .train_particle_net import (
    EXPERIMENT_STEP as TEACHER_LOGIT_PN_TRAIN_EXPERIMENT_STEP,
    TeacherLogitParticleNetTrainConfig,
    train_teacher_logit_particle_net_reco,
)
from .train_particle_flow import (
    EXPERIMENT_STEP as TEACHER_LOGIT_PF_TRAIN_EXPERIMENT_STEP,
    TeacherLogitParticleFlowTrainConfig,
    teacher_logit_particle_flow_checkpoint_payload,
    train_teacher_logit_particle_flow_reco,
)
from .train_particle_cnn import (
    EXPERIMENT_STEP as TEACHER_LOGIT_PCNN_TRAIN_EXPERIMENT_STEP,
    TeacherLogitParticleCnnTrainConfig,
    teacher_logit_particle_cnn_checkpoint_payload,
    train_teacher_logit_particle_cnn_reco,
)
from .predict_particle_net import (
    PREDICT_EXPERIMENT_STEP as TEACHER_LOGIT_PN_PREDICT_EXPERIMENT_STEP,
    TeacherLogitParticleNetPredictionConfig,
    collect_teacher_logit_particle_net_predictions,
    default_model_name_for_teacher_architecture as default_particle_net_reco_model_name_for_teacher_architecture,
    load_particle_net_reconstructor_checkpoint,
)
from .predict_particle_flow import (
    PREDICT_EXPERIMENT_STEP as TEACHER_LOGIT_PF_PREDICT_EXPERIMENT_STEP,
    TeacherLogitParticleFlowPredictionConfig,
    collect_teacher_logit_particle_flow_predictions,
    default_model_name_for_teacher_architecture as default_particle_flow_reco_model_name_for_teacher_architecture,
    load_particle_flow_reconstructor_checkpoint,
)
from .predict_particle_cnn import (
    PREDICT_EXPERIMENT_STEP as TEACHER_LOGIT_PCNN_PREDICT_EXPERIMENT_STEP,
    TeacherLogitParticleCnnPredictionConfig,
    collect_teacher_logit_particle_cnn_predictions,
    default_model_name_for_teacher_architecture as default_particle_cnn_reco_model_name_for_teacher_architecture,
    load_particle_cnn_reconstructor_checkpoint,
)
from .pcnn_first_experiment import (
    EXPERIMENT_STEP as TEACHER_LOGIT_PCNN_FIRST_EXPERIMENT_STEP,
    DEFAULT_FIRST_EXPERIMENT_SPLITS as PCNN_FIRST_EXPERIMENT_SPLITS,
    PredictionComparisonSpec as ParticleCnnPredictionComparisonSpec,
    TeacherLogitParticleCnnFirstExperimentConfig,
    build_first_experiment_report as build_particle_cnn_first_experiment_report,
    comparison_delta_summary as particle_cnn_comparison_delta_summary,
    prediction_metric_summary as particle_cnn_prediction_metric_summary,
    run_teacher_logit_particle_cnn_first_experiment,
)
from .pfn_first_experiment import (
    EXPERIMENT_STEP as TEACHER_LOGIT_PF_FIRST_EXPERIMENT_STEP,
    DEFAULT_FIRST_EXPERIMENT_SPLITS as PFN_FIRST_EXPERIMENT_SPLITS,
    PredictionComparisonSpec as ParticleFlowPredictionComparisonSpec,
    TeacherLogitParticleFlowFirstExperimentConfig,
    build_first_experiment_report as build_particle_flow_first_experiment_report,
    comparison_delta_summary as particle_flow_comparison_delta_summary,
    prediction_metric_summary as particle_flow_prediction_metric_summary,
    run_teacher_logit_particle_flow_first_experiment,
)
from .pn_first_experiment import (
    EXPERIMENT_STEP as TEACHER_LOGIT_PN_FIRST_EXPERIMENT_STEP,
    DEFAULT_FIRST_EXPERIMENT_SPLITS,
    PredictionComparisonSpec,
    TeacherLogitParticleNetFirstExperimentConfig,
    build_first_experiment_report,
    comparison_delta_summary,
    prediction_metric_summary,
    run_teacher_logit_particle_net_first_experiment,
)
from .predict_global_transformer import (
    PREDICT_EXPERIMENT_STEP as TEACHER_LOGIT_GT_PREDICT_EXPERIMENT_STEP,
    HLTPredictionDataset,
    TeacherLogitGlobalTransformerPredictionConfig,
    collect_teacher_logit_global_transformer_predictions,
    default_model_name_for_teacher_architecture,
    evaluate_teacher_logit_reco_model,
    load_global_transformer_reconstructor_checkpoint,
    teacher_architecture_from_payload,
    teacher_checkpoint_from_payload,
)

__all__ = [
    "PairedJetViews",
    "SoftReconstructedView",
    "limit_split_manifest",
    "load_paired_jet_views",
    "make_identity_soft_view",
    "make_soft_view_from_parents_and_extras",
    "soft_view_to_particle_transformer_inputs",
    "summarize_paired_jet_views",
    "summarize_soft_view",
    "validate_view_alignment",
    "FrozenTeacher",
    "FrozenTeacherMetadata",
    "TEACHER_ARCHITECTURES",
    "assert_teacher_frozen",
    "build_teacher_model_from_payload",
    "infer_teacher_architecture",
    "load_frozen_teacher",
    "normalize_teacher_architecture",
    "summarize_teacher_forward",
    "GlobalTransformerReconstructor",
    "GlobalTransformerReconstructorConfig",
    "build_global_transformer_reconstructor",
    "jet_axes_from_tokens",
    "physical_energy_floor",
    "sanitize_hlt_tokens",
    "token_embedding_features",
    "TEACHER_LOGIT_RECONSTRUCTOR_ARCHITECTURES",
    "build_reconstructor_from_config",
    "build_teacher_logit_reconstructor",
    "infer_reconstructor_architecture_from_payload",
    "load_teacher_logit_reconstructor_checkpoint",
    "normalize_reconstructor_architecture",
    "CROSSARCH_DEFAULT_FUSERS",
    "CROSSARCH_DIRECT_HLT_ARCHITECTURES",
    "CROSSARCH_EXPERIMENT_NAME",
    "CROSSARCH_EXPERIMENT_STEP",
    "CROSSARCH_MIXED4_RECO_TEACHER_PAIRS",
    "CROSSARCH_RECONSTRUCTOR_ARCHITECTURES",
    "CROSSARCH_RECONSTRUCTOR_IMPLEMENTATIONS",
    "CROSSARCH_REQUIRED_FUSION_GROUPS",
    "CROSSARCH_SAME_FAMILY_RECO_TEACHER_PAIRS",
    "CROSSARCH_SPLIT_ORDER",
    "CROSSARCH_SPLIT_SIZES",
    "CROSSARCH_TEACHER_ARCHITECTURES",
    "CrossArchExperimentConfig",
    "CrossArchExperimentLayout",
    "CrossArchSourceSpec",
    "FusionGroupSpec",
    "build_crossarch_fusion_groups",
    "build_crossarch_hlt_source_specs",
    "build_crossarch_reco_source_specs",
    "default_crossarch_experiment_config",
    "crossarch_hlt_model_name",
    "normalize_crossarch_reconstructor_architecture",
    "normalize_crossarch_teacher_architecture",
    "crossarch_reco_model_name",
    "validate_crossarch_fusion_groups",
    "CROSSARCH_OFFLINE_TEACHER_EXPERIMENT_STEP",
    "CROSSARCH_OFFLINE_TEACHER_REGISTER_EXPERIMENT_STEP",
    "CROSSARCH_OFFLINE_TEACHER_TRAIN_EXPERIMENT_STEP",
    "CrossArchOfflineTeacherTrainConfig",
    "crossarch_offline_teacher_dir",
    "maybe_load_checkpoint_metadata",
    "normalize_crossarch_offline_teacher_architecture",
    "register_crossarch_offline_teacher_checkpoint",
    "sha256_file",
    "train_crossarch_offline_teacher",
    "CROSSARCH_HLT_BASELINE_EXPERIMENT_STEP",
    "CROSSARCH_HLT_BASELINE_PREDICT_EXPERIMENT_STEP",
    "CROSSARCH_HLT_BASELINE_PREDICTION_SPLITS",
    "CROSSARCH_HLT_BASELINE_TRAIN_EXPERIMENT_STEP",
    "CrossArchHLTBaselinePredictionConfig",
    "CrossArchHLTBaselineTrainConfig",
    "collect_crossarch_hlt_baseline_predictions",
    "crossarch_hlt_baseline_dir",
    "crossarch_hlt_checkpoint_path",
    "normalize_crossarch_hlt_architecture",
    "split_size_for_crossarch_hlt_prediction",
    "train_crossarch_hlt_baseline",
    "CROSSARCH_RECONSTRUCTOR_EXPERIMENT_STEP",
    "CROSSARCH_RECONSTRUCTOR_TRAIN_EXPERIMENT_STEP",
    "CROSSARCH_RECONSTRUCTOR_TRAIN_SCRIPTS",
    "CrossArchReconstructorSpec",
    "build_crossarch_reconstructor_spec",
    "build_crossarch_reconstructor_specs",
    "crossarch_reconstructor_checkpoint",
    "crossarch_reconstructor_dir",
    "crossarch_step5_reconstructor_model_name",
    "crossarch_teacher_checkpoint_path",
    "train_script_for_reconstructor",
    "CROSSARCH_PREDICTION_EXPERIMENT_STEP",
    "CROSSARCH_HLT_PREDICTION_EXPERIMENT_STEP",
    "CROSSARCH_HLT_PREDICT_SCRIPT",
    "CROSSARCH_RECONSTRUCTOR_PREDICT_SCRIPTS",
    "CROSSARCH_RECO_PREDICTION_EXPERIMENT_STEP",
    "CrossArchPredictionSpec",
    "build_crossarch_hlt_prediction_specs",
    "build_crossarch_prediction_specs",
    "build_crossarch_reco_prediction_specs",
    "crossarch_hlt_prediction_spec",
    "crossarch_reco_prediction_spec",
    "predict_script_for_reconstructor",
    "CROSSARCH_ALL_FEATURE_MODES",
    "CROSSARCH_BIN_GATED_FUSER_FEATURE_MODE",
    "CROSSARCH_CONTROL_WARNING_CHANCE_MARGIN",
    "CROSSARCH_CONTROL_WARNING_MIN_ACCURACY",
    "CROSSARCH_DEFAULT_BIN_SCORE_NAMES",
    "CROSSARCH_DEFAULT_CONTROL_FEATURE_MODES",
    "CROSSARCH_DEFAULT_STEP8_FUSERS",
    "CROSSARCH_FUSION_FEATURE_EXPERIMENT_STEP",
    "CROSSARCH_FUSION_FEATURE_MODES",
    "CROSSARCH_FUSER_EXPERIMENT_STEP",
    "CROSSARCH_LOGITS_PROBS_UNCERTAINTY_FEATURE_MODE",
    "CROSSARCH_LOGISTIC_FUSER_FEATURE_MODES",
    "CROSSARCH_UNCERTAINTY_FEATURE_MODE",
    "CrossArchFusionFeatureBuildConfig",
    "CrossArchFusionFitConfig",
    "CrossArchSplitFeatureSet",
    "NamedFeatureMatrix",
    "assign_bins_from_specs",
    "assign_quantile_bins",
    "audit_group_prediction_blocks",
    "bin_assignment_name_for_fuser",
    "build_bin_scores",
    "build_group_feature_report",
    "build_split_feature_set",
    "build_split_feature_set_from_blocks",
    "build_uncertainty_feature_matrix",
    "default_crossarch_feature_groups",
    "distinct_predicted_class_count",
    "entropy_from_probs",
    "evaluate_mean_fuser",
    "fit_bin_gated_logistic_fuser",
    "fit_bin_specs",
    "fit_global_logistic_fuser",
    "fit_group_fusers",
    "final_test_guardrail_audit",
    "crossarch_fusion_labels_hash",
    "load_group_fusion_data",
    "mean_logits_probs",
    "mean_probs_probs",
    "pairwise_disagreement_fraction",
    "predicted_classes",
    "quantile_edges",
    "raw_feature_matrix",
    "run_crossarch_feature_builder",
    "run_crossarch_fusers",
    "run_group_negative_controls",
    "save_feature_set",
    "top1_margin_from_probs",
    "validate_crossarch_feature_groups",
    "PARTICLE_FLOW_FEATURE_NAMES",
    "PARTICLE_FLOW_INPUT_FEATURE_DIM",
    "PARTICLE_FLOW_RECONSTRUCTOR_ARCHITECTURE",
    "PARTICLE_FLOW_SUMMARY_FEATURE_NAMES",
    "PARTICLE_FLOW_SUMMARY_FEATURE_DIM",
    "ParticleFlowContextBuilder",
    "ParticleFlowEncoder",
    "ParticleFlowEncoderOutput",
    "ParticleFlowReconstructor",
    "ParticleFlowReconstructorConfig",
    "build_particle_flow_reconstructor",
    "build_particle_flow_features",
    "build_particle_flow_summary_features",
    "masked_max_pool",
    "masked_mean_pool",
    "masked_sum_pool",
    "PARTICLE_CNN_RECONSTRUCTOR_ARCHITECTURE",
    "PARTICLE_CNN_BASE_FEATURE_NAMES",
    "PARTICLE_CNN_FEATURE_NAMES",
    "PARTICLE_CNN_INPUT_FEATURE_DIM",
    "PARTICLE_CNN_ORDERING_ASSUMPTION",
    "PARTICLE_CNN_RANK_FEATURE_NAMES",
    "ParticleCnnBlock",
    "ParticleCnnContextBuilder",
    "ParticleCnnEncoder",
    "ParticleCnnEncoderOutput",
    "ParticleCnnReconstructor",
    "ParticleCnnReconstructorConfig",
    "apply_particle_mask_channels",
    "audit_particle_cnn_cache_order",
    "build_particle_cnn_features",
    "build_particle_cnn_reconstructor",
    "build_rank_features",
    "particle_cnn_masked_max_pool",
    "particle_cnn_masked_mean_pool",
    "particle_cnn_masked_sum_pool",
    "EdgeConvBlock",
    "PARTICLE_NET_INPUT_FEATURE_DIM",
    "PARTICLE_NET_KNN_COORD_DIM",
    "ParticleNetReconstructor",
    "ParticleNetReconstructorConfig",
    "ParticleNetEncoder",
    "build_particle_net_reconstructor",
    "gather_neighbor_features",
    "masked_knn_indices",
    "particle_net_input_features",
    "particle_net_knn_coordinates",
    "TeacherLogitRecoLossConfig",
    "TeacherLogitRecoLossOutput",
    "compute_teacher_logit_reco_loss",
    "correction_budget_loss",
    "global_transformer_teacher_training_step",
    "teacher_cross_entropy_loss",
    "teacher_kl_loss",
    "weak_jet_summary_loss",
    "weighted_jet_summary",
    "TEACHER_LOGIT_GT_TRAIN_EXPERIMENT_STEP",
    "PairedTeacherLogitDataset",
    "TeacherLogitGlobalTransformerTrainConfig",
    "collate_paired_teacher_logit",
    "make_teacher_logit_loader",
    "run_teacher_logit_reco_epoch",
    "source_metadata",
    "train_teacher_logit_global_transformer_reco",
    "TEACHER_LOGIT_PN_TRAIN_EXPERIMENT_STEP",
    "TeacherLogitParticleNetTrainConfig",
    "train_teacher_logit_particle_net_reco",
    "TEACHER_LOGIT_PF_TRAIN_EXPERIMENT_STEP",
    "TeacherLogitParticleFlowTrainConfig",
    "teacher_logit_particle_flow_checkpoint_payload",
    "train_teacher_logit_particle_flow_reco",
    "TEACHER_LOGIT_PCNN_TRAIN_EXPERIMENT_STEP",
    "TeacherLogitParticleCnnTrainConfig",
    "teacher_logit_particle_cnn_checkpoint_payload",
    "train_teacher_logit_particle_cnn_reco",
    "TEACHER_LOGIT_PN_PREDICT_EXPERIMENT_STEP",
    "TeacherLogitParticleNetPredictionConfig",
    "collect_teacher_logit_particle_net_predictions",
    "default_particle_net_reco_model_name_for_teacher_architecture",
    "load_particle_net_reconstructor_checkpoint",
    "TEACHER_LOGIT_PF_PREDICT_EXPERIMENT_STEP",
    "TeacherLogitParticleFlowPredictionConfig",
    "collect_teacher_logit_particle_flow_predictions",
    "default_particle_flow_reco_model_name_for_teacher_architecture",
    "load_particle_flow_reconstructor_checkpoint",
    "TEACHER_LOGIT_PCNN_PREDICT_EXPERIMENT_STEP",
    "TeacherLogitParticleCnnPredictionConfig",
    "collect_teacher_logit_particle_cnn_predictions",
    "default_particle_cnn_reco_model_name_for_teacher_architecture",
    "load_particle_cnn_reconstructor_checkpoint",
    "TEACHER_LOGIT_PCNN_FIRST_EXPERIMENT_STEP",
    "PCNN_FIRST_EXPERIMENT_SPLITS",
    "ParticleCnnPredictionComparisonSpec",
    "TeacherLogitParticleCnnFirstExperimentConfig",
    "build_particle_cnn_first_experiment_report",
    "particle_cnn_comparison_delta_summary",
    "particle_cnn_prediction_metric_summary",
    "run_teacher_logit_particle_cnn_first_experiment",
    "TEACHER_LOGIT_PF_FIRST_EXPERIMENT_STEP",
    "PFN_FIRST_EXPERIMENT_SPLITS",
    "ParticleFlowPredictionComparisonSpec",
    "TeacherLogitParticleFlowFirstExperimentConfig",
    "build_particle_flow_first_experiment_report",
    "particle_flow_comparison_delta_summary",
    "particle_flow_prediction_metric_summary",
    "run_teacher_logit_particle_flow_first_experiment",
    "TEACHER_LOGIT_PN_FIRST_EXPERIMENT_STEP",
    "DEFAULT_FIRST_EXPERIMENT_SPLITS",
    "PredictionComparisonSpec",
    "TeacherLogitParticleNetFirstExperimentConfig",
    "build_first_experiment_report",
    "comparison_delta_summary",
    "prediction_metric_summary",
    "run_teacher_logit_particle_net_first_experiment",
    "TEACHER_LOGIT_GT_PREDICT_EXPERIMENT_STEP",
    "HLTPredictionDataset",
    "TeacherLogitGlobalTransformerPredictionConfig",
    "collect_teacher_logit_global_transformer_predictions",
    "default_model_name_for_teacher_architecture",
    "evaluate_teacher_logit_reco_model",
    "load_global_transformer_reconstructor_checkpoint",
    "teacher_architecture_from_payload",
    "teacher_checkpoint_from_payload",
]
